export { EventCard } from './event-card/event-card.component'
export { Button } from './button/button-component'
export { AnimalDetails } from './animal-details/animal-details.component'
export { Header } from './header/header.component'
export { AnimalCard } from './animal-card/animal-card.component'
